apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 256Gi
  volumeName: immich-pv
  storageClassName: local-storage
  # storageClassName: slow
  # selector:
  #   matchLabels:
  #     release: "stable"
  #   matchExpressions:
  #     - {key: kubernetes.io/hostname, operator: In, values: [example-node]}
